version: '3.8'

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "300:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
