version: '3.8'

services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:dev
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
