version: '3.7'
services:
  frontend:
    container_name: react_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: react_app_db
      MYSQL_USER: react_user
      MYSQL_PASSWORD: react_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
