version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  react:
    image: "node:21.7.1"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    expose:
      - "3000"
    ports:
      # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm start"
