version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  node_api:
    image: node
    container_name: node_api
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - mariadb
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: examplepassword
      DB_DATABASE: mydatabase

volumes:
  mariadb_data:
