version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  node_api:
    image: node:latest
    container_name: node_api
    restart: always
    ports:
      - "3000:3030"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: examplepassword
      DB_DATABASE: mydatabase

volumes:
  mariadb_data:
