# Use a lightweight base image
FROM node:alpine AS build

# Set working directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json to leverage Docker layer caching
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Build your application (if necessary)
# RUN npm run build

# Stage 2: Use a smaller base image for runtime
FROM node:alpine

# Set working directory
WORKDIR /home/node/app

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
