version: '3.7'
services:
  frontend:
    container_name: react_frontend
    image: node:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    depends_on:
      - db

  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: react_app_db
      MYSQL_USER: react_user
      MYSQL_PASSWORD: react_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

