# Use a lightweight Node.js base image
FROM node

# Set the working directory
WORKDIR /app/frontend

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 3000 (if not already done in docker-compose.yml)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
